import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav/Nav";
import DarkLight from "./components/darkLight/DarkLight";
import "./globals.css";
import { getSections } from "./lib/data";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sections = await getSections();
  console.log(sections)

  return (
    <html id="app" className="dark" lang="en">
      <body
        className={`${inter.className} dark:bg-black dark:text-white flex h-screen`}
      >
        <header className="border-4 px-2 py-1">
          <DarkLight />
          <Nav sections={sections.filter((section) => section.isActive)} />
        </header>

        {children}
      </body>
    </html>
  );
}
