import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " text-white  bg-gradient-to-br from-slate-900 to-slate-800 flex flex-col items-center h-screen"
        }
      >
        <header className="mt-20 w-full border-b ">
          <Nav />
        </header>

        <main className="  w-full h-full flex flex-col items-center justify-start">
          {children}
        </main>
      </body>
    </html>
  );
}
