import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "@/app/components/wrapper/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function privateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //await for the session
  return (
    <>
      <Main>{children}</Main>
    </>
  );
}
