import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/app/components/nav/Nav";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/lib/auth";
import Main from "@/app/components/wrapper/Main";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function privateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //await for the session
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
  }
  return (
    <>
      <header className="mt-6 w-full  ">
        <Nav />
      </header>
      <Main>{children}</Main>
    </>
  );
}
